### ISSUE TITLE
[FEAT]: CI pipelines 

### ISSUE THREAD

**Issue by Srijan-SS02** [blossomlabsio/Bloom-Backend#35]
### Describe the feature you'd like to request

Add CI pipeline to build and push docker image to docker hub container registry .

### Describe the solution you'd like

Using github actions to write a workflow to do so

**Comment by Srijan-SS02** [comment]
Hey @Mr-Sunglasses, I would like to solve this issue.
Please assign!

**Comment by Mr-Sunglasses** [comment]
@Srijan-SS02

**Comment by Mr-Sunglasses** [comment]
@Srijan-SS02 Bhai Sher 🐯, sher he khede bhai ko, sheeeerrrrr

**Comment by Srijan-SS02** [comment]
workflow exists
