### ISSUE TITLE
Add Support for pre-commit

### ISSUE THREAD

**Issue by Mr-Sunglasses** [blossomlabsio/Bloom-Backend#4]

**Comment by Siddharth9890** [comment]
hey @Mr-Sunglasses can i try this do we need to use something like husky to solve this

**Comment by Mr-Sunglasses** [comment]
Hey @Siddharth9890 , In the Python ecosystem we usually setup pre-commit hooks with [pre-commit](https://pre-commit.com/) If you any more help just ping me up.

**Comment by Siddharth9890** [comment]
Sure can you assign it to me?
